# Site settings
title: Khala-wan`
description: 'Swift Niu bi'
url: 'http://Khala-wan.com'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: '万圣'
  email: wansheng_ios@sina.com
  # twitter_username: joshgerdes
  # facebook_username: joshgerdes
  github_username:  Khala-wan
  linkedin_username:  Khala-wan

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
# exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
